apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::681993069705:role/udacity-node-group
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::681993069705:role/voclabs
      username: voclabs
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::681993069705:user/github-action-user
      username: github-action-role
      groups:
        - system:masters
    - userarn: arn:aws:iam::681993069705:user/admin
      username: admin
      groups:
        - system:masters
